export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          name: string;
          prefecture: string;
          referee_grade: string;
          categories: string[];
          years_of_experience: number | null;
          avatar_type: string;
          avatar_key: string;
          avatar_url: string | null;
          plan_type: string;
          monthly_video_analysis_count: number;
          monthly_video_analysis_period_start: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username?: string | null;
          name?: string;
          prefecture?: string;
          referee_grade?: string;
          categories?: string[];
          years_of_experience?: number | null;
          avatar_type?: string;
          avatar_key?: string;
          avatar_url?: string | null;
          plan_type?: string;
          monthly_video_analysis_count?: number;
          monthly_video_analysis_period_start?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string | null;
          name?: string;
          prefecture?: string;
          referee_grade?: string;
          categories?: string[];
          years_of_experience?: number | null;
          avatar_type?: string;
          avatar_key?: string;
          avatar_url?: string | null;
          plan_type?: string;
          monthly_video_analysis_count?: number;
          monthly_video_analysis_period_start?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      plan_limits: {
        Row: {
          plan_type: string;
          monthly_analysis_limit: number | null;
          label: string;
          updated_at: string;
        };
        Insert: {
          plan_type: string;
          monthly_analysis_limit?: number | null;
          label?: string;
          updated_at?: string;
        };
        Update: {
          plan_type?: string;
          monthly_analysis_limit?: number | null;
          label?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      matches: {
        Row: {
          id: string;
          user_id: string;
          date: string | null;
          competition: string;
          category: string;
          venue: string;
          home_team: string;
          away_team: string;
          match_count: number;
          partner_referee: string;
          referee_position: string;
          match_role: string;
          start_time: string | null;
          judgment_rating: number;
          position_rating: number;
          communication_rating: number;
          mechanics_rating: number;
          game_control_rating: number;
          stamina_rating: number;
          good_points: string;
          improvements: string;
          next_goal: string;
          difficult_calls: string;
          free_notes: string;
          keywords: string[];
          video_url: string;
          entry_type: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date?: string | null;
          competition?: string;
          category?: string;
          venue?: string;
          home_team?: string;
          away_team?: string;
          match_count?: number;
          partner_referee?: string;
          referee_position?: string;
          match_role?: string;
          start_time?: string | null;
          judgment_rating?: number;
          position_rating?: number;
          communication_rating?: number;
          mechanics_rating?: number;
          game_control_rating?: number;
          stamina_rating?: number;
          good_points?: string;
          improvements?: string;
          next_goal?: string;
          difficult_calls?: string;
          free_notes?: string;
          keywords?: string[];
          video_url?: string;
          entry_type?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string | null;
          competition?: string;
          category?: string;
          venue?: string;
          home_team?: string;
          away_team?: string;
          match_count?: number;
          partner_referee?: string;
          referee_position?: string;
          match_role?: string;
          start_time?: string | null;
          judgment_rating?: number;
          position_rating?: number;
          communication_rating?: number;
          mechanics_rating?: number;
          game_control_rating?: number;
          stamina_rating?: number;
          good_points?: string;
          improvements?: string;
          next_goal?: string;
          difficult_calls?: string;
          free_notes?: string;
          keywords?: string[];
          video_url?: string;
          entry_type?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      annual_goals: {
        Row: {
          id: string;
          user_id: string;
          year: number;
          target_match_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          year: number;
          target_match_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          year?: number;
          target_match_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      schedules: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          scheduled_date: string | null;
          scheduled_time: string | null;
          place: string;
          memo: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string;
          scheduled_date?: string | null;
          scheduled_time?: string | null;
          place?: string;
          memo?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          scheduled_date?: string | null;
          scheduled_time?: string | null;
          place?: string;
          memo?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth_key: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth_key: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          endpoint?: string;
          p256dh?: string;
          auth_key?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      notification_settings: {
        Row: {
          user_id: string;
          enabled: boolean;
          day_before_match_enabled: boolean;
          match_day_reminder_enabled: boolean;
          no_record_reminder_enabled: boolean;
          monthly_reflection_enabled: boolean;
          ai_advice_enabled: boolean;
          notify_time: string;
          match_day_time: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          enabled?: boolean;
          day_before_match_enabled?: boolean;
          match_day_reminder_enabled?: boolean;
          no_record_reminder_enabled?: boolean;
          monthly_reflection_enabled?: boolean;
          ai_advice_enabled?: boolean;
          notify_time?: string;
          match_day_time?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          enabled?: boolean;
          day_before_match_enabled?: boolean;
          match_day_reminder_enabled?: boolean;
          no_record_reminder_enabled?: boolean;
          monthly_reflection_enabled?: boolean;
          ai_advice_enabled?: boolean;
          notify_time?: string;
          match_day_time?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notification_log: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          reference_id: string | null;
          sent_for_date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          reference_id?: string | null;
          sent_for_date: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          reference_id?: string | null;
          sent_for_date?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          url: string;
          reference_id: string | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          url?: string;
          reference_id?: string | null;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          body?: string;
          url?: string;
          reference_id?: string | null;
          is_read?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      video_analyses: {
        Row: {
          id: string;
          user_id: string;
          match_id: string | null;
          title: string;
          storage_path: string;
          original_filename: string;
          mime_type: string;
          file_size_bytes: number;
          duration_seconds: number | null;
          width_px: number | null;
          height_px: number | null;
          estimated_fps: number | null;
          status: string;
          progress: number;
          is_demo: boolean;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          match_id?: string | null;
          title?: string;
          storage_path: string;
          original_filename?: string;
          mime_type?: string;
          file_size_bytes?: number;
          duration_seconds?: number | null;
          width_px?: number | null;
          height_px?: number | null;
          estimated_fps?: number | null;
          status?: string;
          progress?: number;
          is_demo?: boolean;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          match_id?: string | null;
          title?: string;
          storage_path?: string;
          original_filename?: string;
          mime_type?: string;
          file_size_bytes?: number;
          duration_seconds?: number | null;
          width_px?: number | null;
          height_px?: number | null;
          estimated_fps?: number | null;
          status?: string;
          progress?: number;
          is_demo?: boolean;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      analysis_quality_metrics: {
        Row: {
          id: string;
          video_analysis_id: string;
          user_id: string;
          sampled_frame_count: number;
          mean_brightness: number | null;
          brightness_stddev: number | null;
          dark_frame_ratio: number | null;
          overexposed_frame_ratio: number | null;
          blur_proxy_score: number | null;
          quality_tier: string;
          quality_reasons: string[];
          raw_metrics: Record<string, unknown>;
          computed_at: string;
        };
        Insert: {
          id?: string;
          video_analysis_id: string;
          user_id: string;
          sampled_frame_count?: number;
          mean_brightness?: number | null;
          brightness_stddev?: number | null;
          dark_frame_ratio?: number | null;
          overexposed_frame_ratio?: number | null;
          blur_proxy_score?: number | null;
          quality_tier: string;
          quality_reasons?: string[];
          raw_metrics?: Record<string, unknown>;
          computed_at?: string;
        };
        Update: {
          id?: string;
          video_analysis_id?: string;
          user_id?: string;
          sampled_frame_count?: number;
          mean_brightness?: number | null;
          brightness_stddev?: number | null;
          dark_frame_ratio?: number | null;
          overexposed_frame_ratio?: number | null;
          blur_proxy_score?: number | null;
          quality_tier?: string;
          quality_reasons?: string[];
          raw_metrics?: Record<string, unknown>;
          computed_at?: string;
        };
        Relationships: [];
      };
      analysis_events: {
        Row: {
          id: string;
          video_analysis_id: string;
          user_id: string;
          stage: string;
          event_type: string;
          timestamp_seconds: number | null;
          conclusion: string;
          evidence: string;
          confidence: Record<string, unknown>;
          why_uncertain: string;
          alternative_interpretation: string;
          missing_data: string;
          human_review_recommended: boolean;
          is_demo: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          video_analysis_id: string;
          user_id: string;
          stage: string;
          event_type: string;
          timestamp_seconds?: number | null;
          conclusion?: string;
          evidence?: string;
          confidence?: Record<string, unknown>;
          why_uncertain?: string;
          alternative_interpretation?: string;
          missing_data?: string;
          human_review_recommended?: boolean;
          is_demo?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          video_analysis_id?: string;
          user_id?: string;
          stage?: string;
          event_type?: string;
          timestamp_seconds?: number | null;
          conclusion?: string;
          evidence?: string;
          confidence?: Record<string, unknown>;
          why_uncertain?: string;
          alternative_interpretation?: string;
          missing_data?: string;
          human_review_recommended?: boolean;
          is_demo?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      coaching_results: {
        Row: {
          id: string;
          video_analysis_id: string;
          user_id: string;
          summary: string;
          strengths: string[];
          growth_areas: string[];
          conclusion: string;
          evidence: string;
          confidence: Record<string, unknown>;
          why_uncertain: string;
          alternative_interpretation: string;
          missing_data: string;
          human_review_recommended: boolean;
          is_demo: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          video_analysis_id: string;
          user_id: string;
          summary?: string;
          strengths?: string[];
          growth_areas?: string[];
          conclusion?: string;
          evidence?: string;
          confidence?: Record<string, unknown>;
          why_uncertain?: string;
          alternative_interpretation?: string;
          missing_data?: string;
          human_review_recommended?: boolean;
          is_demo?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          video_analysis_id?: string;
          user_id?: string;
          summary?: string;
          strengths?: string[];
          growth_areas?: string[];
          conclusion?: string;
          evidence?: string;
          confidence?: Record<string, unknown>;
          why_uncertain?: string;
          alternative_interpretation?: string;
          missing_data?: string;
          human_review_recommended?: boolean;
          is_demo?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      analysis_feedback: {
        Row: {
          id: string;
          video_analysis_id: string;
          user_id: string;
          target_type: string;
          target_id: string;
          rating: string;
          comment: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          video_analysis_id: string;
          user_id: string;
          target_type: string;
          target_id: string;
          rating: string;
          comment?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          video_analysis_id?: string;
          user_id?: string;
          target_type?: string;
          target_id?: string;
          rating?: string;
          comment?: string;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
};
